import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { KorekChain,transactionMessage } from "../src/blockchain.js";
import { addressFromPublicKey,cryptoProvider,wormholeAddressFromInnerHash } from "../src/crypto.js";
import { NETWORK,rewardAtHeight } from "../src/config.js";

test("Planck network and token allocations are fixed",()=>{assert.equal(NETWORK.networkId,"korek-planck-testnet-1");assert.equal(NETWORK.miningAllocation+NETWORK.aiEcosystemAllocation+NETWORK.developmentAllocation+NETWORK.securityCommunityAllocation,NETWORK.maxSupply);assert.equal(rewardAtHeight(0),115740740n);assert.equal(rewardAtHeight(NETWORK.halvingInterval),57870370n)});
test("mining rewards a wormhole address derived from a 32-byte inner hash",()=>{const chain=new KorekChain(),innerHash="ab".repeat(32),address=wormholeAddressFromInnerHash(innerHash),block=chain.mine(address);assert.equal(address,`krk1${"ab".repeat(20)}`);assert.equal(chain.balance(address),block.reward);assert.throws(()=>wormholeAddressFromInnerHash("bad"),/32 bytes/)});
test("transparent signed transfer remains compatible",()=>{const chain=new KorekChain(),alice=cryptoProvider.createWallet(),bob=cryptoProvider.createWallet();chain.claimFaucet(alice.address);const timestamp=Date.now(),amount="100000000",gasPrice="1",gasLimit="21000",message=`${alice.address}|${bob.address}|${amount}|${timestamp}|${gasPrice}|${gasLimit}`;const tx=chain.addTransaction({version:2,from:alice.address,to:bob.address,amount,timestamp,gasPrice,gasLimit,publicKey:alice.publicKey,signature:cryptoProvider.sign(message,alice.privateKey)});chain.sealPending();assert.equal(chain.transaction(tx.id).status,"confirmed");assert.equal(chain.balance(bob.address),amount)});
test("wormhole version 3 balance can be signed and spent",()=>{const chain=new KorekChain(),owner=cryptoProvider.createWallet(),recipient=cryptoProvider.createWallet();const innerHash=createHash("sha256").update(`korek-wormhole-v1:${owner.publicKey}`).digest("hex"),from=wormholeAddressFromInnerHash(innerHash);assert.equal(from,addressFromPublicKey(owner.publicKey,"wormhole-v1"));chain.mine(from);const timestamp=Date.now(),amount="100000000",gasPrice="1",gasLimit="21000",scheme="wormhole-v1",message=`${from}|${recipient.address}|${amount}|${timestamp}|${gasPrice}|${gasLimit}|${scheme}`;const tx=chain.addTransaction({version:3,from,to:recipient.address,amount,timestamp,gasPrice,gasLimit,addressScheme:scheme,publicKey:owner.publicKey,signature:cryptoProvider.sign(message,owner.privateKey)});chain.sealPending();assert.equal(chain.transaction(tx.id).addressScheme,scheme);assert.equal(chain.balance(recipient.address),amount)});
test("faucet remains hourly and excluded from mined supply",()=>{const chain=new KorekChain(),wallet=cryptoProvider.createWallet(),now=2_000_000_000_000;chain.claimFaucet(wallet.address,100n*100_000_000n,now);assert.equal(chain.minedSupply,0n);assert.throws(()=>chain.claimFaucet(wallet.address,100n*100_000_000n,now+1),/cooldown/)});
test("verified snapshots preserve blocks, balances and supply across restart",()=>{const chain=new KorekChain(),wallet=cryptoProvider.createWallet();chain.mine(wallet.address);chain.claimFaucet(wallet.address);const restored=KorekChain.fromSnapshot(chain.snapshot());assert.equal(restored.chain.length,chain.chain.length);assert.equal(restored.balance(wallet.address),chain.balance(wallet.address));assert.equal(restored.minedSupply,chain.minedSupply);const damaged=structuredClone(chain.snapshot());damaged.chain[1].reward="999";assert.throws(()=>KorekChain.fromSnapshot(damaged),/Invalid persisted block/)});

const signedV4=({wallet,to,nonce=0,amount="1000000",gasPrice="1",now=Date.now(),networkId=NETWORK.networkId})=>{const input={version:4,networkId,from:wallet.address,to,amount,nonce,timestamp:now,expiresAt:now+60_000,gasPrice,gasLimit:"21000",addressScheme:"transparent-v1",publicKey:wallet.publicKey};return{...input,signature:cryptoProvider.sign(transactionMessage(input),wallet.privateKey)}};
test("version 4 rejects cross-network, replayed, expired and nonce-gap transactions",()=>{const chain=new KorekChain(),alice=cryptoProvider.createWallet(),bob=cryptoProvider.createWallet(),now=2_000_000_000_000;chain.claimFaucet(alice.address,100n*100_000_000n,now);const valid=signedV4({wallet:alice,to:bob.address,now});chain.addTransaction(valid,now);assert.equal(chain.nextNonce(alice.address),1);assert.throws(()=>chain.addTransaction(valid,now),/nonce|Duplicate|replay/i);assert.throws(()=>chain.addTransaction(signedV4({wallet:alice,to:bob.address,nonce:2,now}),now),/expected 1/);assert.throws(()=>chain.addTransaction(signedV4({wallet:cryptoProvider.createWallet(),to:bob.address,now,networkId:"another-chain"}),now),/different network/);const expired=signedV4({wallet:cryptoProvider.createWallet(),to:bob.address,now:now-120_000});assert.throws(()=>chain.addTransaction(expired,now),/expired/)});
test("mempool orders independent senders by fee while preserving sender nonce order",()=>{const chain=new KorekChain(),alice=cryptoProvider.createWallet(),bob=cryptoProvider.createWallet(),recipient=cryptoProvider.createWallet(),now=2_000_000_000_000;chain.claimFaucet(alice.address,100n*100_000_000n,now);chain.claimFaucet(bob.address,100n*100_000_000n,now);chain.addTransactionBatch([signedV4({wallet:alice,to:recipient.address,nonce:0,gasPrice:"1",now}),signedV4({wallet:alice,to:recipient.address,nonce:1,gasPrice:"9",now:now+1}),signedV4({wallet:bob,to:recipient.address,nonce:0,gasPrice:"5",now:now+2})],now+2);assert.deepEqual(chain.pending.map(tx=>[tx.from,tx.nonce]),[[bob.address,0],[alice.address,0],[alice.address,1]]);chain.sealPending(now+3);assert.equal(chain.nextNonce(alice.address),2);assert.equal(chain.nextNonce(bob.address),1)});
test("failed transaction batches roll back every admission",()=>{const chain=new KorekChain(),alice=cryptoProvider.createWallet(),bob=cryptoProvider.createWallet(),now=2_000_000_000_000;chain.claimFaucet(alice.address,100n*100_000_000n,now);assert.throws(()=>chain.addTransactionBatch([signedV4({wallet:alice,to:bob.address,nonce:0,now}),signedV4({wallet:alice,to:bob.address,nonce:3,now})],now),/expected 1/);assert.equal(chain.pending.length,0);assert.equal(chain.nextNonce(alice.address),0)});
test("parallel batch verification accepts independent signatures atomically",async()=>{const chain=new KorekChain(),recipient=cryptoProvider.createWallet(),wallets=Array.from({length:8},()=>cryptoProvider.createWallet()),now=2_000_000_000_000;wallets.forEach(wallet=>chain.claimFaucet(wallet.address,100n*100_000_000n,now));const batch=wallets.map(wallet=>signedV4({wallet,to:recipient.address,now})),accepted=await chain.addTransactionBatchParallel(batch,now);assert.equal(accepted.length,8);const damaged=batch.map(item=>({...item}));damaged[3].signature=batch[2].signature;await assert.rejects(()=>chain.addTransactionBatchParallel(damaged,now),/index 3/);assert.equal(chain.pending.length,8)});
test("version 2 snapshots remain readable after the nonce upgrade",()=>{const chain=new KorekChain(),alice=cryptoProvider.createWallet(),bob=cryptoProvider.createWallet(),now=2_000_000_000_000;chain.claimFaucet(alice.address,100n*100_000_000n,now);chain.addTransaction(signedV4({wallet:alice,to:bob.address,now}),now);chain.sealPending(now+1);const restored=KorekChain.fromSnapshot(chain.snapshot());assert.equal(restored.nextNonce(alice.address),1);assert.throws(()=>restored.addTransaction(signedV4({wallet:alice,to:bob.address,nonce:0,now:now+2}),now+2),/expected 1/)});
