import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { KorekChain } from "../src/blockchain.js";
import { addressFromPublicKey,cryptoProvider,wormholeAddressFromInnerHash } from "../src/crypto.js";
import { NETWORK,rewardAtHeight,splitSubsidy } from "../src/config.js";

test("Planck zero-premine monetary policy is fixed",()=>{assert.equal(NETWORK.networkId,"korek-planck-testnet-1");assert.equal(NETWORK.maxSupply,210_000_000n*100_000_000n);assert.equal(NETWORK.miningAllocation,NETWORK.maxSupply);assert.equal(NETWORK.genesisPremine,0n);assert.equal(NETWORK.minerShareBps+NETWORK.treasuryShareBps,10_000n);assert.equal(NETWORK.rewardBlockTimeMs,60_000);assert.equal(NETWORK.difficulty,Number(process.env.KOREK_DIFFICULTY||7));assert.equal(rewardAtHeight(0),50n*100_000_000n);assert.equal(rewardAtHeight(NETWORK.halvingInterval),25n*100_000_000n)});
test("the complete halving schedule cannot exceed the 210 million cap",()=>{let issued=0n;for(let era=0;era<64;era++)issued+=rewardAtHeight(era*NETWORK.halvingInterval)*BigInt(NETWORK.halvingInterval);assert.ok(issued<=NETWORK.maxSupply);assert.ok(NETWORK.maxSupply-issued<100_000_000n);for(const subsidy of [50n*100_000_000n,25n*100_000_000n,1n]){const split=splitSubsidy(subsidy);assert.equal(split.miner+split.treasury,subsidy)}});
test("block subsidy is split 95/5 with zero genesis balances",()=>{const chain=new KorekChain(),miner=cryptoProvider.createWallet().address,block=chain.mine(miner),split=splitSubsidy(50n*100_000_000n);assert.equal(chain.balance(miner),split.miner.toString());assert.equal(chain.balance(NETWORK.treasuryAddress),split.treasury.toString());assert.equal(block.minerReward,split.miner.toString());assert.equal(block.treasuryReward,split.treasury.toString());assert.equal(chain.chain[0].reward,"0")});
test("mining rewards a wormhole address derived from a 32-byte inner hash",()=>{const chain=new KorekChain(),innerHash="ab".repeat(32),address=wormholeAddressFromInnerHash(innerHash),block=chain.mine(address);assert.equal(address,`krk1${"ab".repeat(20)}`);assert.equal(chain.balance(address),(BigInt(block.minerReward)+BigInt(block.feePayout)).toString());assert.throws(()=>wormholeAddressFromInnerHash("bad"),/32 bytes/)});
test("transparent signed transfer remains compatible",()=>{const chain=new KorekChain(),alice=cryptoProvider.createWallet(),bob=cryptoProvider.createWallet();chain.claimFaucet(alice.address);const timestamp=Date.now(),amount="100000000",gasPrice="1",gasLimit="21000",message=`${alice.address}|${bob.address}|${amount}|${timestamp}|${gasPrice}|${gasLimit}`;const tx=chain.addTransaction({version:2,from:alice.address,to:bob.address,amount,timestamp,gasPrice,gasLimit,publicKey:alice.publicKey,signature:cryptoProvider.sign(message,alice.privateKey)});chain.sealPending();assert.equal(chain.transaction(tx.id).status,"confirmed");assert.equal(chain.balance(bob.address),amount)});
test("wormhole version 3 balance can be signed and spent",()=>{const chain=new KorekChain(),owner=cryptoProvider.createWallet(),recipient=cryptoProvider.createWallet();const innerHash=createHash("sha256").update(`korek-wormhole-v1:${owner.publicKey}`).digest("hex"),from=wormholeAddressFromInnerHash(innerHash);assert.equal(from,addressFromPublicKey(owner.publicKey,"wormhole-v1"));chain.mine(from);const timestamp=Date.now(),amount="100000000",gasPrice="1",gasLimit="21000",scheme="wormhole-v1",message=`${from}|${recipient.address}|${amount}|${timestamp}|${gasPrice}|${gasLimit}|${scheme}`;const tx=chain.addTransaction({version:3,from,to:recipient.address,amount,timestamp,gasPrice,gasLimit,addressScheme:scheme,publicKey:owner.publicKey,signature:cryptoProvider.sign(message,owner.privateKey)});chain.sealPending();assert.equal(chain.transaction(tx.id).addressScheme,scheme);assert.equal(chain.balance(recipient.address),amount)});
test("faucet remains hourly and excluded from mined supply",()=>{const chain=new KorekChain(),wallet=cryptoProvider.createWallet(),now=2_000_000_000_000;chain.claimFaucet(wallet.address,100n*100_000_000n,now);assert.equal(chain.minedSupply,0n);assert.throws(()=>chain.claimFaucet(wallet.address,100n*100_000_000n,now+1),/cooldown/)});
test("verified snapshots preserve blocks, balances and supply across restart",()=>{const chain=new KorekChain(),wallet=cryptoProvider.createWallet();chain.mine(wallet.address);chain.claimFaucet(wallet.address);const restored=KorekChain.fromSnapshot(chain.snapshot());assert.equal(restored.chain.length,chain.chain.length);assert.equal(restored.balance(wallet.address),chain.balance(wallet.address));assert.equal(restored.minedSupply,chain.minedSupply);const damaged=structuredClone(chain.snapshot());damaged.chain[1].reward="999";assert.throws(()=>KorekChain.fromSnapshot(damaged),/Invalid persisted block/)});
test("transaction fees wait in the chain pool and go entirely to the next miner",()=>{const chain=new KorekChain(),sender=cryptoProvider.createWallet(),recipient=cryptoProvider.createWallet(),nextMiner=cryptoProvider.createWallet();chain.claimFaucet(sender.address);const timestamp=Date.now(),amount="100000000",gasPrice="1",gasLimit="21000",message=`${sender.address}|${recipient.address}|${amount}|${timestamp}|${gasPrice}|${gasLimit}`;chain.addTransaction({version:2,from:sender.address,to:recipient.address,amount,timestamp,gasPrice,gasLimit,publicKey:sender.publicKey,signature:cryptoProvider.sign(message,sender.privateKey)});const finality=chain.sealPending();assert.equal(finality.feePayout,"0");assert.equal(chain.feePool,21_000n);const reward=chain.mine(nextMiner.address);assert.equal(reward.feePayout,"21000");assert.equal(chain.balance(nextMiner.address),(BigInt(reward.minerReward)+21_000n).toString());assert.equal(chain.feePool,0n)});
