import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { KorekChain } from "../src/blockchain.js";
import { addressFromPublicKey,cryptoProvider,wormholeAddressFromInnerHash } from "../src/crypto.js";
import { NETWORK,rewardAtHeight } from "../src/config.js";

test("Planck network and token allocations are fixed",()=>{assert.equal(NETWORK.networkId,"korek-planck-testnet-1");assert.equal(NETWORK.miningAllocation+NETWORK.aiEcosystemAllocation+NETWORK.developmentAllocation+NETWORK.securityCommunityAllocation,NETWORK.maxSupply);assert.equal(rewardAtHeight(0),115740740n);assert.equal(rewardAtHeight(NETWORK.halvingInterval),57870370n)});
test("mining rewards a wormhole address derived from a 32-byte inner hash",()=>{const chain=new KorekChain(),innerHash="ab".repeat(32),address=wormholeAddressFromInnerHash(innerHash),block=chain.mine(address);assert.equal(address,`krk1${"ab".repeat(20)}`);assert.equal(chain.balance(address),block.reward);assert.throws(()=>wormholeAddressFromInnerHash("bad"),/32 bytes/)});
test("transparent signed transfer remains compatible",()=>{const chain=new KorekChain(),alice=cryptoProvider.createWallet(),bob=cryptoProvider.createWallet();chain.claimFaucet(alice.address);const timestamp=Date.now(),amount="100000000",gasPrice="1",gasLimit="21000",message=`${alice.address}|${bob.address}|${amount}|${timestamp}|${gasPrice}|${gasLimit}`;const tx=chain.addTransaction({version:2,from:alice.address,to:bob.address,amount,timestamp,gasPrice,gasLimit,publicKey:alice.publicKey,signature:cryptoProvider.sign(message,alice.privateKey)});chain.sealPending();assert.equal(chain.transaction(tx.id).status,"confirmed");assert.equal(chain.balance(bob.address),amount)});
test("wormhole version 3 balance can be signed and spent",()=>{const chain=new KorekChain(),owner=cryptoProvider.createWallet(),recipient=cryptoProvider.createWallet();const innerHash=createHash("sha256").update(`korek-wormhole-v1:${owner.publicKey}`).digest("hex"),from=wormholeAddressFromInnerHash(innerHash);assert.equal(from,addressFromPublicKey(owner.publicKey,"wormhole-v1"));chain.mine(from);const timestamp=Date.now(),amount="100000000",gasPrice="1",gasLimit="21000",scheme="wormhole-v1",message=`${from}|${recipient.address}|${amount}|${timestamp}|${gasPrice}|${gasLimit}|${scheme}`;const tx=chain.addTransaction({version:3,from,to:recipient.address,amount,timestamp,gasPrice,gasLimit,addressScheme:scheme,publicKey:owner.publicKey,signature:cryptoProvider.sign(message,owner.privateKey)});chain.sealPending();assert.equal(chain.transaction(tx.id).addressScheme,scheme);assert.equal(chain.balance(recipient.address),amount)});
test("faucet remains hourly and excluded from mined supply",()=>{const chain=new KorekChain(),wallet=cryptoProvider.createWallet(),now=2_000_000_000_000;chain.claimFaucet(wallet.address,100n*100_000_000n,now);assert.equal(chain.minedSupply,0n);assert.throws(()=>chain.claimFaucet(wallet.address,100n*100_000_000n,now+1),/cooldown/)});
