import test from "node:test";
import assert from "node:assert/strict";
import { KorekChain } from "../src/blockchain.js";
import { cryptoProvider } from "../src/crypto.js";
import { NETWORK } from "../src/config.js";
import { ComputeMarket,COMPUTE_WORKER_SHARE_BPS,computeJobMessage,computeClaimMessage,computeResultMessage,computeVoteMessage,computeChallengeMessage,computeCancelMessage } from "../src/compute-market.js";
import { ComputeValidatorRegistry,COMPUTE_VALIDATOR_MIN_STAKE,COMPUTE_VALIDATOR_SET_SIZE,COMPUTE_VALIDATOR_THRESHOLD,COMPUTE_VALIDATOR_FRAUD_SLASH_BPS,validatorRegisterMessage } from "../src/validator-registry.js";
import { COMPUTE_CHALLENGE_WINDOW_MS,deterministicOutputHash,witnessHash } from "../src/fraud-proof.js";

const DEFAULT_WITNESS={items:["alpha","beta","gamma"]};
const signed=(wallet,message,fields)=>({...fields,publicKey:wallet.publicKey,signature:cryptoProvider.sign(message,wallet.privateKey)});
const registerValidator=(chain,registry,wallet,now)=>{chain.claimFaucet(wallet.address,COMPUTE_VALIDATOR_MIN_STAKE+1_000n*100_000_000n,now-10_000);const fields={validator:wallet.address,addressScheme:"transparent-v1",stake:COMPUTE_VALIDATOR_MIN_STAKE.toString(),timestamp:now};return registry.register(signed(wallet,validatorRegisterMessage(fields),fields),now)};
const setup=(now,count=5)=>{const chain=new KorekChain(),registry=new ComputeValidatorRegistry(chain),validators=Array.from({length:count},()=>cryptoProvider.createWallet());validators.forEach((wallet,index)=>registerValidator(chain,registry,wallet,now+index));const market=new ComputeMarket(chain,registry,null,{entropyProvider:()=>"11".repeat(32)});return{chain,registry,validators,market}};
const fundCreator=(chain,creator,now)=>chain.claimFaucet(creator.address,100n*100_000_000n,now-10_000);
const makeJob=(market,creator,now,{payment="1000000000",witness=DEFAULT_WITNESS,profile="sha256-batch-v1",deadline=now+60_000,...extra}={})=>{const fields={creator:creator.address,addressScheme:"transparent-v1",workloadProfile:profile,inputHash:witnessHash(profile,witness),payment,deadline,timestamp:now,...extra};return{job:market.createJob(signed(creator,computeJobMessage(fields),fields),now),witness}};
const claim=(market,job,worker,now)=>{const fields={jobId:job.id,worker:worker.address,addressScheme:"transparent-v1",timestamp:now};return market.claimJob(job.id,signed(worker,computeClaimMessage(fields),fields),now)};
const result=(market,job,worker,now,outputHash)=>{const fields={jobId:job.id,worker:worker.address,addressScheme:"transparent-v1",outputHash,timestamp:now};return market.submitResult(job.id,signed(worker,computeResultMessage(fields),fields),now)};
const vote=(market,job,verifier,now,approve=true,outputHash=job.outputHash)=>{const fields={jobId:job.id,verifier:verifier.address,addressScheme:"transparent-v1",outputHash,approve,timestamp:now};return market.vote(job.id,signed(verifier,computeVoteMessage(fields),fields),now)};
const challenge=(market,job,challenger,witness,now)=>{const fields={jobId:job.id,challenger:challenger.address,addressScheme:"transparent-v1",witnessHash:witnessHash(job.workloadProfile,witness),timestamp:now},payload={...fields,witness};return market.challengeJob(job.id,signed(challenger,computeChallengeMessage(fields),payload),now)};
const walletFor=(wallets,address)=>wallets.find(wallet=>wallet.address===address);
const votersFor=(validators,job)=>job.verifiers.slice(0,3).map(address=>walletFor(validators,address));

test("3-of-5 approval opens a challenge window and pays only after finalization",()=>{
 const now=2_000_000_000_000,{chain,registry,validators,market}=setup(now),creator=cryptoProvider.createWallet(),worker=cryptoProvider.createWallet();fundCreator(chain,creator,now);const minedBefore=chain.minedSupply,{job,witness}=makeJob(market,creator,now+100),correct=deterministicOutputHash(job.workloadProfile,witness);assert.equal(job.verifiers.length,COMPUTE_VALIDATOR_SET_SIZE);assert.equal(job.verificationThreshold,COMPUTE_VALIDATOR_THRESHOLD);
 claim(market,job,worker,now+101);result(market,job,worker,now+102,correct);const voters=votersFor(validators,job);vote(market,job,voters[0],now+103);vote(market,job,voters[1],now+104);const provisional=vote(market,job,voters[2],now+105);assert.equal(provisional.status,"challenge-window");assert.equal(provisional.provisionalOutcome,"accepted");assert.equal(chain.balance(worker.address),"0");assert.equal(market.stats().escrowed,job.payment);assert.throws(()=>market.finalizeJob(job.id,now+105+COMPUTE_CHALLENGE_WINDOW_MS),/still open/);
 const settled=market.finalizeJob(job.id,now+106+COMPUTE_CHALLENGE_WINDOW_MS),payment=BigInt(job.payment),workerPayout=payment*COMPUTE_WORKER_SHARE_BPS/10_000n,verifierTotal=Object.values(settled.verifierPayouts).reduce((sum,value)=>sum+BigInt(value),0n);assert.equal(settled.status,"settled");assert.equal(BigInt(chain.balance(worker.address)),workerPayout);assert.equal(verifierTotal,payment-workerPayout);assert.equal(chain.minedSupply,minedBefore);assert.equal(market.stats().escrowed,"0");job.verifiers.forEach(address=>assert.equal(registry.isAssigned(job.id,address),false));
});

test("fraud proof overturns bad approval, refunds customer and slashes approving validators",()=>{
 const now=2_100_000_000_000,{chain,registry,validators,market}=setup(now),creator=cryptoProvider.createWallet(),worker=cryptoProvider.createWallet();fundCreator(chain,creator,now);const before=BigInt(chain.balance(creator.address)),minedBefore=chain.minedSupply,{job,witness}=makeJob(market,creator,now+100,{payment:"500000000"}),wrong="00".repeat(32);claim(market,job,worker,now+101);result(market,job,worker,now+102,wrong);const voters=votersFor(validators,job);vote(market,job,voters[0],now+103);vote(market,job,voters[1],now+104);vote(market,job,voters[2],now+105);const treasuryBefore=BigInt(chain.balance(NETWORK.treasuryAddress)),challenged=challenge(market,job,creator,witness,now+106),slashEach=COMPUTE_VALIDATOR_MIN_STAKE*COMPUTE_VALIDATOR_FRAUD_SLASH_BPS/10_000n;
 assert.equal(challenged.accepted,true);assert.equal(challenged.job.status,"rejected");assert.equal(BigInt(chain.balance(creator.address)),before);assert.equal(chain.balance(worker.address),"0");assert.equal(challenged.proof.slashes.length,3);assert.equal(BigInt(chain.balance(NETWORK.treasuryAddress)),treasuryBefore+slashEach*3n);voters.forEach(wallet=>{const entry=registry.validator(wallet.address);assert.equal(entry.status,"jailed");assert.equal(BigInt(entry.slashedStake),slashEach)});assert.equal(chain.minedSupply,minedBefore);assert.throws(()=>market.challengeJob(job.id,{},now+107),/not in the challenge window/);
});

test("fraud proof overturns dishonest rejection and pays worker/challenger from escrow",()=>{
 const now=2_200_000_000_000,{chain,registry,validators,market}=setup(now),creator=cryptoProvider.createWallet(),worker=cryptoProvider.createWallet();fundCreator(chain,creator,now);const {job,witness}=makeJob(market,creator,now+100,{payment:"700000000"}),correct=deterministicOutputHash(job.workloadProfile,witness);claim(market,job,worker,now+101);result(market,job,worker,now+102,correct);const voters=votersFor(validators,job);vote(market,job,voters[0],now+103,false,"01".repeat(32));vote(market,job,voters[1],now+104,false,"02".repeat(32));const provisional=vote(market,job,voters[2],now+105,false,"03".repeat(32));assert.equal(provisional.provisionalOutcome,"rejected");const challenged=challenge(market,job,worker,witness,now+106);assert.equal(challenged.job.status,"settled");assert.equal(BigInt(chain.balance(worker.address)),BigInt(job.payment));assert.equal(challenged.proof.slashes.length,3);voters.forEach(wallet=>assert.equal(registry.validator(wallet.address).fraudProofs,1));
});

test("invalid or non-overturning challenge cannot slash validators",()=>{
 const now=2_300_000_000_000,{chain,registry,validators,market}=setup(now),creator=cryptoProvider.createWallet(),worker=cryptoProvider.createWallet();fundCreator(chain,creator,now);const {job,witness}=makeJob(market,creator,now+100),correct=deterministicOutputHash(job.workloadProfile,witness);claim(market,job,worker,now+101);result(market,job,worker,now+102,correct);const voters=votersFor(validators,job);vote(market,job,voters[0],now+103);vote(market,job,voters[1],now+104);vote(market,job,voters[2],now+105);
 const badWitness={items:["not-the-committed-input"]},badFields={jobId:job.id,challenger:creator.address,addressScheme:"transparent-v1",witnessHash:witnessHash(job.workloadProfile,badWitness),timestamp:now+106},badPayload={...badFields,witness:badWitness};assert.throws(()=>market.challengeJob(job.id,signed(creator,computeChallengeMessage(badFields),badPayload),now+106),/does not match the committed input hash/);voters.forEach(wallet=>assert.equal(registry.validator(wallet.address).fraudProofs,0));
 const confirms=challenge(market,job,creator,witness,now+107);assert.equal(confirms.accepted,false);assert.equal(confirms.overturned,false);assert.equal(market.job(job.id).status,"challenge-window");voters.forEach(wallet=>assert.equal(registry.validator(wallet.address).fraudProofs,0));
});

test("customer cannot choose validators, lower threshold, or cancel after random selection",()=>{
 const now=2_400_000_000_000,{chain,registry,market}=setup(now),creator=cryptoProvider.createWallet();fundCreator(chain,creator,now);const attacker=cryptoProvider.createWallet(),chosenWitness={items:["chosen"]},chosen={creator:creator.address,addressScheme:"transparent-v1",workloadProfile:"sha256-batch-v1",inputHash:witnessHash("sha256-batch-v1",chosenWitness),payment:"100000000",deadline:now+60_000,timestamp:now,verifiers:[attacker.address]};assert.throws(()=>market.createJob(signed(creator,computeJobMessage(chosen),chosen),now),/selected by the network/);
 const weakWitness={items:["weak"]},weak={creator:creator.address,addressScheme:"transparent-v1",workloadProfile:"sha256-batch-v1",inputHash:witnessHash("sha256-batch-v1",weakWitness),payment:"100000000",deadline:now+60_000,timestamp:now+1,verificationThreshold:2};assert.throws(()=>market.createJob(signed(creator,computeJobMessage(weak),weak),now+1),/fixed at 3 of 5/);
 const {job}=makeJob(market,creator,now+2,{payment:"250000000",deadline:now+1002,witness:{items:["cancel"]}}),afterEscrow=BigInt(chain.balance(creator.address)),cancelFields={jobId:job.id,creator:creator.address,addressScheme:"transparent-v1",timestamp:now+3};assert.throws(()=>market.cancelJob(job.id,signed(creator,computeCancelMessage(cancelFields),cancelFields),now+3),/cannot be cancelled after validator selection/);assert.equal(BigInt(chain.balance(creator.address)),afterEscrow);const expired=market.expireJob(job.id,now+1003);assert.equal(expired.status,"expired");assert.equal(BigInt(chain.balance(creator.address)),afterEscrow+250_000_000n);job.verifiers.forEach(address=>assert.equal(registry.isAssigned(job.id,address),false));
});

test("unselected wallets cannot vote and selected validators cannot claim worker role",()=>{
 const now=2_500_000_000_000,{chain,registry,validators,market}=setup(now,6),creator=cryptoProvider.createWallet(),worker=cryptoProvider.createWallet();fundCreator(chain,creator,now);const {job,witness}=makeJob(market,creator,now+100),selectedWallet=walletFor(validators,job.verifiers[0]),outsider=validators.find(wallet=>!job.verifiers.includes(wallet.address)),selectedClaim={jobId:job.id,worker:selectedWallet.address,addressScheme:"transparent-v1",timestamp:now+101};assert.throws(()=>market.claimJob(job.id,signed(selectedWallet,computeClaimMessage(selectedClaim),selectedClaim),now+101),/selected validator/);claim(market,job,worker,now+102);result(market,job,worker,now+103,deterministicOutputHash(job.workloadProfile,witness));assert.equal(registry.isAssigned(job.id,outsider.address),false);const outsiderVote={jobId:job.id,verifier:outsider.address,addressScheme:"transparent-v1",outputHash:job.outputHash,approve:true,timestamp:now+104};assert.throws(()=>market.vote(job.id,signed(outsider,computeVoteMessage(outsiderVote),outsiderVote),now+104),/network-selected staked validator/);
});

test("challenge-window state survives snapshot restore without changing supply",()=>{
 const now=2_600_000_000_000,{chain,registry,validators,market}=setup(now),creator=cryptoProvider.createWallet(),worker=cryptoProvider.createWallet();fundCreator(chain,creator,now);const {job,witness}=makeJob(market,creator,now+100,{payment:"123456789"}),correct=deterministicOutputHash(job.workloadProfile,witness);claim(market,job,worker,now+101);result(market,job,worker,now+102,correct);const voters=votersFor(validators,job);vote(market,job,voters[0],now+103);vote(market,job,voters[1],now+104);vote(market,job,voters[2],now+105);const restoredChain=KorekChain.fromSnapshot(chain.snapshot()),restoredRegistry=new ComputeValidatorRegistry(restoredChain,registry.snapshot()),restored=new ComputeMarket(restoredChain,restoredRegistry,market.snapshot(),{entropyProvider:()=>"22".repeat(32)});assert.equal(restored.job(job.id).status,"challenge-window");assert.equal(restored.stats().escrowed,"123456789");job.verifiers.forEach(address=>assert.equal(restoredRegistry.isAssigned(job.id,address),true));assert.equal(restoredChain.minedSupply,chain.minedSupply);
});
