import test from "node:test";
import assert from "node:assert/strict";
import { generateKeyPairSync,sign } from "node:crypto";
import { addressFromPublicKey } from "../src/crypto.js";
import { KorekChain } from "../src/blockchain.js";
import { createTemplate,meetsDifficulty,miningRequestMessage,miningSubmissionMessage,powDigest,verifySubmission,verifyWorkRequest } from "../src/mining-protocol.js";

const identity=()=>{const pair=generateKeyPairSync("ed25519"),publicKey=pair.publicKey.export({type:"spki",format:"pem"}),privateKey=pair.privateKey.export({type:"pkcs8",format:"pem"}),address=addressFromPublicKey(publicKey,"wormhole-v1");return{publicKey,privateKey,address}};
const signature=(message,key)=>sign(null,Buffer.from(message),key).toString("base64");
test("accepts a wallet-signed work request",()=>{const owner=identity(),input={address:owner.address,publicKey:owner.publicKey,timestamp:1000,requestNonce:"ab".repeat(16)};input.signature=signature(miningRequestMessage(input),owner.privateKey);assert.doesNotThrow(()=>verifyWorkRequest(input,1000))});
test("rejects a mining identity that does not own the reward address",()=>{const owner=identity(),other=identity(),input={address:other.address,publicKey:owner.publicKey,timestamp:1000,requestNonce:"ab".repeat(16)};input.signature=signature(miningRequestMessage(input),owner.privateKey);assert.throws(()=>verifyWorkRequest(input,1000),/does not own/)});
test("verifies a submitted proof and signature",()=>{const owner=identity(),template=createTemplate({networkId:"test",height:1,previousHash:"00".repeat(32),rewardAddress:owner.address,publicKey:owner.publicKey,reward:"1",difficulty:1,now:1000});let nonce=0,powHash;do{powHash=powDigest(template.challenge,nonce++)}while(!meetsDifficulty(powHash,1));const input={templateId:template.templateId,address:owner.address,publicKey:owner.publicKey,nonce:nonce-1,powHash,timestamp:1100};input.signature=signature(miningSubmissionMessage(input),owner.privateKey);assert.equal(verifySubmission(input,template,1100),powHash)});
test("rejects stale and tampered submissions",()=>{const owner=identity(),template=createTemplate({networkId:"test",height:1,previousHash:"00".repeat(32),rewardAddress:owner.address,publicKey:owner.publicKey,reward:"1",difficulty:1,now:1000}),input={templateId:template.templateId,address:owner.address,publicKey:owner.publicKey,nonce:0,powHash:"00".repeat(32),timestamp:40000,signature:"bad"};assert.throws(()=>verifySubmission(input,template,40000),/expired/)});
test("matches the public protocol SHA-256 test vector",()=>assert.equal(powDigest("00".repeat(32),0),"6db65fd59fd356f6729140571b5bcd6bb3b83492a16e1bf0a3884442fc3c8a0e"));
test("chain accepts a valid client proof and credits only its owner",()=>{const owner=identity(),chain=new KorekChain(),now=Date.now(),template=createTemplate({...chain.miningTemplateData(owner.address,now),publicKey:owner.publicKey});let nonce=0,powHash;do{powHash=powDigest(template.challenge,nonce++)}while(!meetsDifficulty(powHash,template.difficulty));const input={templateId:template.templateId,address:owner.address,publicKey:owner.publicKey,nonce:nonce-1,powHash,timestamp:Math.max(Date.now(),template.notBefore),hashesTried:nonce,device:"test-cpu"};input.signature=signature(miningSubmissionMessage(input),owner.privateKey);const block=chain.acceptClientProof(template,input);assert.equal(block.workProof.powHash,powHash);assert.equal(chain.balance(owner.address),block.reward);assert.equal(chain.status().rewardBlockCount,1)});
