import test from "node:test";
import assert from "node:assert/strict";
import { generateKeyPairSync,createHash } from "node:crypto";
import { KorekChain } from "../src/blockchain.js";
import { P2PNetwork,verifyEnvelope } from "../src/p2p.js";

const identity=()=>{const {publicKey,privateKey}=generateKeyPairSync("ed25519"),pub=publicKey.export({type:"spki",format:"pem"}),priv=privateKey.export({type:"pkcs8",format:"pem"});return{peerId:createHash("sha256").update(pub).digest("hex"),publicKey:pub,privateKey:priv}};
test("P2P rejects unsigned and malformed envelopes",()=>{assert.throws(()=>verifyEnvelope({}),/Malformed/);assert.throws(()=>verifyEnvelope({payload:{peerId:"bad"},publicKey:"bad",signature:"bad"}),/identity|key/i)});
test("a second node discovers and synchronizes the longer signed Planck chain",async()=>{let source=new KorekChain(),target=new KorekChain();source.mine(`krk1${"ab".repeat(20)}`,undefined,Date.now(),{difficulty:0,rewardEnabled:false});const first=new P2PNetwork({identity:identity(),name:"first",port:0,advertiseUrl:null,getChain:()=>source,onSnapshot:async()=>{}}),address=await first.start(),seed=`http://127.0.0.1:${address.port}`,second=new P2PNetwork({identity:identity(),name:"second",port:0,advertiseUrl:null,seeds:[seed],syncIntervalMs:60_000,getChain:()=>target,onSnapshot:async snapshot=>{target=KorekChain.fromSnapshot(snapshot)}});try{await second.start();assert.equal(target.chain.length,source.chain.length);assert.equal(second.networkStatus().connectedPeers,1);assert.equal(second.networkStatus().state,"Idle")}finally{await second.stop();await first.stop()}});
test("incremental synchronization downloads bounded ranges without a full snapshot",async()=>{let source=new KorekChain(),target=new KorekChain();for(let index=0;index<3;index++)source.mine(`krk1${"ab".repeat(20)}`,undefined,Date.now(),{difficulty:0,rewardEnabled:false});const first=new P2PNetwork({identity:identity(),name:"source",port:0,advertiseUrl:null,getChain:()=>source,onSnapshot:async()=>{}});first.snapshotPayload=()=>{throw new Error("full snapshot fallback must not be used")};const address=await first.start(),second=new P2PNetwork({identity:identity(),name:"target",port:0,advertiseUrl:null,seeds:[`http://127.0.0.1:${address.port}`],syncBatchSize:1,syncIntervalMs:60_000,getChain:()=>target,onSnapshot:async snapshot=>{target=KorekChain.fromSnapshot(snapshot)}});try{await second.start();assert.equal(target.chain.length,4);assert.equal(target.chain.at(-1).hash,source.chain.at(-1).hash)}finally{await second.stop();await first.stop()}});
test("a longer zero-work peer cannot replace a chain with verified cumulative work",async()=>{const source=new KorekChain(),target=new KorekChain();for(let index=0;index<5;index++)source.mine(`krk1${"cd".repeat(20)}`);target.cumulativeWork=()=>4096n;let replacements=0;const first=new P2PNetwork({identity:identity(),name:"weak-long",port:0,advertiseUrl:null,getChain:()=>source,onSnapshot:async()=>{}}),address=await first.start(),second=new P2PNetwork({identity:identity(),name:"strong-short",port:0,advertiseUrl:null,seeds:[`http://127.0.0.1:${address.port}`],syncIntervalMs:60_000,getChain:()=>target,onSnapshot:async()=>{replacements++}});try{await second.start();assert.equal(replacements,0);assert.equal(target.chain.length,1)}finally{await second.stop();await first.stop()}});
