import { MINER_PROTOCOL,NODE_VERSION } from "../src/protocol.js";
const arg=(name)=>{const prefix=`--${name}=`;const inline=process.argv.find(x=>x.startsWith(prefix));if(inline)return inline.slice(prefix.length);const at=process.argv.indexOf(`--${name}`);return at>=0?process.argv[at+1]:undefined};
if(process.argv.includes("--version")){console.log(`korek-miner ${NODE_VERSION} · ${MINER_PROTOCOL}`);process.exit(0)}
const base=new URL(arg("node-url")||process.env.KOREK_NODE_URL||"http://127.0.0.1:9833").origin,innerHash=(arg("rewards-inner-hash")||process.env.KOREK_REWARDS_INNER_HASH||"").toLowerCase();
if(!/^[0-9a-f]{64}$/.test(innerHash)){console.error("Use --rewards-inner-hash with exactly 64 hexadecimal characters.");process.exit(1)}
const headers={"content-type":"application/json","x-korek-miner-protocol":MINER_PROTOCOL};
const request=async(path,options={})=>{const response=await fetch(`${base}${path}`,{...options,headers:{...headers,...options.headers}}),data=await response.json();if(response.status===426)throw new Error(`${data.error}. Download a matching node/miner release.`);if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data};
const status=await request("/status");console.log(`KOREK miner ${NODE_VERSION}`);console.log(`Connected to ${status.networkId} node ${status.name} at ${base}`);console.log(`Protocol: ${status.minerProtocol} · sync: ${status.sync.state}`);if(status.sync.state!=="Idle"){console.error("Node is not ready; mining is paused.");process.exit(2)}
let stopping=false;process.on("SIGINT",()=>{stopping=true;console.log("\nMiner stopped.")});
while(!stopping){const started=Date.now();try{const current=await request("/status");if(current.sync.state!=="Idle")console.log(`Mining paused · node state ${current.sync.state}`);else{const block=await request("/mine",{method:"POST",body:JSON.stringify({rewardsInnerHash:innerHash})});console.log(`Block #${block.height} · reward ${Number(block.reward)/1e8} KRK · ${block.hash}`)}}catch(error){console.error(`Miner error: ${error.message}`)}await new Promise(resolve=>setTimeout(resolve,Math.max(100,(status.rewardBlockTimeMs||1000)-(Date.now()-started))))}
