import { NETWORK,rewardAtHeight } from "./config.js";
import { addressFromPublicKey,cryptoProvider,sha256 } from "./crypto.js";
import { verifySignaturesParallel } from "./signature-workers.js";

export const GAS=Object.freeze({transferLimit:21_000n,price:1n});
export const TRANSACTION_POLICY=Object.freeze({version:4,maxBytes:64*1024,maxPending:10_000,maxFutureMs:60_000,maxLifetimeMs:60*60_000});
export const transactionMessage=input=>Number(input.version)>=4
 ?`${input.networkId}|${input.from}|${input.to}|${input.amount}|${input.nonce}|${input.timestamp}|${input.expiresAt}|${input.gasPrice}|${input.gasLimit}|${input.addressScheme}`
 :Number(input.version)>=3?`${input.from}|${input.to}|${input.amount}|${input.timestamp}|${input.gasPrice}|${input.gasLimit}|${input.addressScheme}`
 :Number(input.version)>=2?`${input.from}|${input.to}|${input.amount}|${input.timestamp}|${input.gasPrice}|${input.gasLimit}`
 :`${input.from}|${input.to}|${input.amount}|${input.timestamp}`;
const feeOrder=(a,b)=>BigInt(a.gasPrice)===BigInt(b.gasPrice)?a.receivedAt-b.receivedAt||a.id.localeCompare(b.id):BigInt(a.gasPrice)>BigInt(b.gasPrice)?-1:1;
const orderPending=transactions=>{if(!Array.isArray(transactions))return 0;const queues=new Map();for(const tx of transactions){const key=tx.version>=4?tx.from:`legacy:${tx.id}`;if(!queues.has(key))queues.set(key,[]);queues.get(key).push(tx)}for(const queue of queues.values())queue.sort((a,b)=>a.version>=4&&b.version>=4?Number(a.nonce)-Number(b.nonce):feeOrder(a,b));const ordered=[];while(queues.size){const heads=[...queues.entries()].map(([key,queue])=>({key,tx:queue[0]})).sort((a,b)=>feeOrder(a.tx,b.tx)),selected=heads[0],queue=queues.get(selected.key);ordered.push(queue.shift());if(!queue.length)queues.delete(selected.key)}return ordered};
const hashBlock=(block)=>sha256(JSON.stringify({height:block.height,rewardHeight:block.rewardHeight,previousHash:block.previousHash,timestamp:block.timestamp,transactions:block.transactions,miner:block.miner,usefulWork:block.usefulWork,reward:block.reward,gasUsed:block.gasUsed,fees:block.fees,nonce:block.nonce}));
export class KorekChain{
 constructor(){this.pending=[];this.balances=new Map();this.nonces=new Map();this.transactionIds=new Set();this.minedSupply=0n;this.testnetFaucetSupply=0n;this.rewardBlockCount=0;this.faucetClaims=new Map();this.chain=[this.genesis()]}
 genesis(){const block={height:0,rewardHeight:null,previousHash:"0".repeat(64),timestamp:1735689600000,transactions:[],miner:"genesis",usefulWork:{type:"genesis",score:0},reward:"0",gasUsed:"0",fees:"0",nonce:0};return{...block,hash:hashBlock(block)}}
 addTransaction(input,receivedAt=Date.now(),options={}){
  const required=["from","to","amount","publicKey","signature","timestamp"];if(!required.every(key=>input[key]!==undefined))throw new Error("Incomplete transaction");if(!/^krk1[0-9a-f]{40}$/.test(input.to)||BigInt(input.amount)<=0n)throw new Error("Invalid transfer");
  const version=Number(input.version||1),gasPrice=version>=2?BigInt(input.gasPrice):0n,gasLimit=version>=2?BigInt(input.gasLimit):0n,addressScheme=version>=3?String(input.addressScheme||"transparent-v1"):"transparent-v1";
  if(!["transparent-v1","wormhole-v1"].includes(addressScheme))throw new Error("Unsupported address scheme");if(version>=2&&(gasPrice<GAS.price||gasLimit<GAS.transferLimit))throw new Error("Gas price or gas limit is too low");
  if(Buffer.byteLength(JSON.stringify(input))>TRANSACTION_POLICY.maxBytes)throw new Error("Transaction exceeds maximum size");if(this.pending.length>=TRANSACTION_POLICY.maxPending)throw new Error("Mempool is full");
  const timestamp=Number(input.timestamp);if(!Number.isSafeInteger(timestamp)||timestamp>receivedAt+TRANSACTION_POLICY.maxFutureMs)throw new Error("Invalid transaction timestamp");
  let nonce=null,expiresAt=null;if(version>=4){if(input.networkId!==NETWORK.networkId)throw new Error("Transaction belongs to a different network");nonce=Number(input.nonce);expiresAt=Number(input.expiresAt);if(!Number.isSafeInteger(nonce)||nonce<0)throw new Error("Invalid transaction nonce");if(!Number.isSafeInteger(expiresAt)||expiresAt<=receivedAt)throw new Error("Transaction has expired");if(expiresAt-timestamp>TRANSACTION_POLICY.maxLifetimeMs)throw new Error("Transaction lifetime is too long");const expected=this.nextNonce(input.from);if(nonce!==expected)throw new Error(`Invalid transaction nonce: expected ${expected}`)}
  const gasUsed=version>=2?GAS.transferLimit:0n,fee=gasUsed*gasPrice;const normalized={...input,version,networkId:version>=4?NETWORK.networkId:undefined,nonce,expiresAt,addressScheme,gasPrice:gasPrice.toString(),gasLimit:gasLimit.toString()};const message=transactionMessage(normalized);
  if(addressFromPublicKey(input.publicKey,addressScheme)!==input.from)throw new Error("Public key mismatch");if(!options.signatureVerified&&!cryptoProvider.verify(message,input.signature,input.publicKey))throw new Error("Invalid signature");
  const reserved=this.pending.filter(tx=>tx.from===input.from).reduce((sum,tx)=>sum+BigInt(tx.amount)+BigInt(tx.fee),0n);if((this.balances.get(input.from)||0n)-reserved<BigInt(input.amount)+fee)throw new Error("Insufficient balance for amount and network fee");
  const tx={...normalized,gasUsed:gasUsed.toString(),fee:fee.toString(),sentAt:timestamp,receivedAt,status:"pending",blockHeight:null,transactionIndex:null,confirmedAt:null};tx.id=sha256(message+input.signature);if(this.transactionIds.has(tx.id))throw new Error("Duplicate or replayed transaction");this.transactionIds.add(tx.id);this.pending=options.deferOrdering?[...this.pending,tx]:orderPending([...this.pending,tx]);return tx;
 }
 addTransactionBatch(inputs,receivedAt=Date.now()){if(!Array.isArray(inputs)||inputs.length<1||inputs.length>1_000)throw new Error("Batch must contain 1 to 1000 transactions");const pending=[...this.pending],ids=new Set(this.transactionIds);try{const accepted=inputs.map(input=>this.addTransaction(input,receivedAt,{deferOrdering:true}));this.pending=orderPending(this.pending);return accepted}catch(error){this.pending=pending;this.transactionIds=ids;throw error}}
 async addTransactionBatchParallel(inputs,receivedAt=Date.now()){if(!Array.isArray(inputs)||inputs.length<1||inputs.length>1_000)throw new Error("Batch must contain 1 to 1000 transactions");const checks=inputs.map(input=>({message:transactionMessage(input),signature:input.signature,publicKey:input.publicKey})),valid=await verifySignaturesParallel(checks);if(valid.some(result=>!result))throw new Error(`Invalid signature at batch index ${valid.indexOf(false)}`);const pending=[...this.pending],ids=new Set(this.transactionIds);try{const accepted=inputs.map(input=>this.addTransaction(input,receivedAt,{signatureVerified:true,deferOrdering:true}));this.pending=orderPending(this.pending);return accepted}catch(error){this.pending=pending;this.transactionIds=ids;throw error}}
 nextNonce(address){return(this.nonces.get(address)||0)+this.pending.filter(tx=>tx.version>=4&&tx.from===address).length}
 mine(miner,usefulWork={type:"benchmark",score:0},now=Date.now(),options={}){if(!/^krk1[0-9a-f]{40}$/.test(miner))throw new Error("Invalid miner address");const height=this.chain.length,rewardEnabled=options.rewardEnabled!==false,difficulty=options.difficulty??NETWORK.difficulty,scheduledReward=rewardAtHeight(this.rewardBlockCount),remaining=NETWORK.miningAllocation-this.minedSupply,reward=!rewardEnabled||remaining<=0n?0n:[scheduledReward,remaining].reduce((a,b)=>a<b?a:b),transactions=this.pending.filter(tx=>tx.expiresAt===null||tx.expiresAt>now).sort(orderPending);this.pending=[];let fees=0n,gasUsed=0n;transactions.forEach((tx,index)=>{tx.status="confirmed";tx.blockHeight=height;tx.transactionIndex=index;tx.confirmedAt=now;tx.confirmationTimeMs=Math.max(0,now-tx.receivedAt);fees+=BigInt(tx.fee);gasUsed+=BigInt(tx.gasUsed)});const block={height,rewardHeight:rewardEnabled?this.rewardBlockCount:null,previousHash:this.chain.at(-1).hash,timestamp:now,transactions,miner,usefulWork,reward:reward.toString(),gasUsed:gasUsed.toString(),fees:fees.toString(),nonce:0};const target="0".repeat(difficulty);do{block.nonce++;block.hash=hashBlock(block)}while(!block.hash.startsWith(target));for(const tx of transactions){this.balances.set(tx.from,(this.balances.get(tx.from)||0n)-BigInt(tx.amount)-BigInt(tx.fee));this.balances.set(tx.to,(this.balances.get(tx.to)||0n)+BigInt(tx.amount));if(tx.version>=4)this.nonces.set(tx.from,Number(tx.nonce)+1)}this.balances.set(miner,(this.balances.get(miner)||0n)+reward+fees);this.minedSupply+=reward;if(rewardEnabled)this.rewardBlockCount++;this.chain.push(block);return block}
 sealPending(now=Date.now()){return this.pending.length===0?null:this.mine(NETWORK.nodeMinerAddress,{type:"rapid-testnet-finality",score:1},now,{difficulty:0,rewardEnabled:false})}
 balance(address){return(this.balances.get(address)||0n).toString()}
 transactions(limit=50){return[...this.pending].reverse().concat(this.chain.slice(1).reverse().flatMap(block=>[...block.transactions].reverse())).slice(0,limit)}
 transaction(id){const tx=this.pending.find(x=>x.id===id)||this.chain.flatMap(block=>block.transactions).find(x=>x.id===id);return tx?{...tx,confirmations:tx.blockHeight===null?0:this.chain.length-tx.blockHeight}:null}
 block(id){const block=/^\d+$/.test(String(id))?this.chain[Number(id)]:this.chain.find(x=>x.hash===id);return block?{...block,confirmations:this.chain.length-block.height,sizeBytes:Buffer.byteLength(JSON.stringify(block))}:null}
 claimFaucet(address,amount=100n*100_000_000n,now=Date.now()){if(!/^krk1[0-9a-f]{40}$/.test(address))throw new Error("Invalid KOREK address");const cooldown=3_600_000,previous=this.faucetClaims.get(address)||0;if(now-previous<cooldown)throw new Error(`Faucet cooldown active. Try again in ${Math.max(1,Math.ceil((cooldown-(now-previous))/60_000))} minutes`);this.balances.set(address,(this.balances.get(address)||0n)+amount);this.testnetFaucetSupply+=amount;this.faucetClaims.set(address,now);return{address,amount:amount.toString(),balance:this.balance(address),network:NETWORK.networkId,claimedAt:now,nextClaimAt:now+cooldown}}
 snapshot(){return{version:2,networkId:NETWORK.networkId,chain:this.chain,pending:this.pending,balances:[...this.balances].map(([address,balance])=>[address,balance.toString()]),nonces:[...this.nonces],minedSupply:this.minedSupply.toString(),testnetFaucetSupply:this.testnetFaucetSupply.toString(),rewardBlockCount:this.rewardBlockCount,faucetClaims:[...this.faucetClaims]}}
 static fromSnapshot(state){if(![1,2].includes(state?.version)||state.networkId!==NETWORK.networkId||!Array.isArray(state.chain)||state.chain.length===0)throw new Error("Unsupported chain state");const restored=new KorekChain();for(let index=0;index<state.chain.length;index++){const block=state.chain[index];if(block.height!==index||block.hash!==hashBlock(block)||(index>0&&block.previousHash!==state.chain[index-1].hash))throw new Error(`Invalid persisted block at height ${index}`)}const mined=BigInt(state.minedSupply),rewardTotal=state.chain.reduce((sum,block)=>sum+BigInt(block.reward),0n);if(mined!==rewardTotal||mined<0n||mined>NETWORK.miningAllocation)throw new Error("Persisted mining supply is invalid");restored.chain=state.chain;restored.pending=Array.isArray(state.pending)?state.pending.sort(orderPending):[];restored.balances=new Map((state.balances||[]).map(([address,balance])=>[address,BigInt(balance)]));restored.nonces=new Map(state.nonces||[]);restored.transactionIds=new Set([...restored.chain.flatMap(block=>block.transactions||[]),...restored.pending].map(tx=>tx.id));restored.minedSupply=mined;restored.testnetFaucetSupply=BigInt(state.testnetFaucetSupply||0);restored.rewardBlockCount=Number(state.rewardBlockCount||0);restored.faucetClaims=new Map(state.faucetClaims||[]);return restored}
 status(){return{...NETWORK,maxSupply:NETWORK.maxSupply.toString(),miningAllocation:NETWORK.miningAllocation.toString(),aiEcosystemAllocation:NETWORK.aiEcosystemAllocation.toString(),developmentAllocation:NETWORK.developmentAllocation.toString(),securityCommunityAllocation:NETWORK.securityCommunityAllocation.toString(),minedSupply:this.minedSupply.toString(),issued:this.minedSupply.toString(),testnetFaucetSupply:this.testnetFaucetSupply.toString(),rewardBlockCount:this.rewardBlockCount,height:this.chain.length-1,pending:this.pending.length,transactions:this.chain.reduce((sum,b)=>sum+b.transactions.length,0),gasPrice:GAS.price.toString(),transferGas:GAS.transferLimit.toString(),transactionVersion:TRANSACTION_POLICY.version,maxTransactionBytes:TRANSACTION_POLICY.maxBytes,maxPendingTransactions:TRANSACTION_POLICY.maxPending,crypto:cryptoProvider.algorithm}}
}
