import { NETWORK,rewardAtHeight,splitSubsidy } from "./config.js";
import { addressFromPublicKey,cryptoProvider,sha256 } from "./crypto.js";
import { MINER_PROTOCOL_V3,meetsDifficulty,miningSubmissionMessage,powDigest,workChallenge } from "./mining-protocol.js";

export const GAS=Object.freeze({transferLimit:21_000n,price:1n});
export const MEMPOOL=Object.freeze({maxTransactions:10_000,maxFutureMs:120_000,maxAgeMs:86_400_000,maxPublicKeyBytes:8_192,maxSignatureBytes:1_024,maxNumericDigits:40});
export const hashBlock=(block)=>sha256(JSON.stringify({height:block.height,rewardHeight:block.rewardHeight,previousHash:block.previousHash,timestamp:block.timestamp,transactions:block.transactions,miner:block.miner,usefulWork:block.usefulWork,reward:block.reward,minerReward:block.minerReward,treasuryReward:block.treasuryReward,treasuryAddress:block.treasuryAddress,gasUsed:block.gasUsed,fees:block.fees,feePayout:block.feePayout,nonce:block.nonce,workProof:block.workProof}));
export const blockWork=block=>block?.workProof?.protocol===MINER_PROTOCOL_V3?16n**BigInt(block.workProof.difficulty):0n;
const expectedReward=chain=>{const scheduled=rewardAtHeight(chain.rewardBlockCount),remaining=NETWORK.miningAllocation-chain.minedSupply;return remaining<=0n?0n:[scheduled,remaining].reduce((a,b)=>a<b?a:b)};
const expectedPayout=chain=>{const reward=expectedReward(chain),split=splitSubsidy(reward);return{reward,minerReward:split.miner,treasuryReward:split.treasury,feePayout:chain.feePool}};
const validateClientProof=block=>{const proof=block.workProof;if(!proof||proof.protocol!==MINER_PROTOCOL_V3)throw new Error("Missing client work proof");if(addressFromPublicKey(proof.publicKey,"wormhole-v1")!==block.miner)throw new Error("Work proof public key mismatch");const split=splitSubsidy(BigInt(block.reward));if(BigInt(block.minerReward)!==split.miner||BigInt(block.treasuryReward)!==split.treasury||block.treasuryAddress!==NETWORK.treasuryAddress)throw new Error("Invalid miner or treasury reward split");const template={protocol:proof.protocol,networkId:NETWORK.networkId,templateId:proof.templateId,height:block.height,previousHash:block.previousHash,rewardAddress:block.miner,publicKey:proof.publicKey,reward:block.reward,minerReward:block.minerReward,treasuryReward:block.treasuryReward,treasuryAddress:block.treasuryAddress,feePayout:block.feePayout,difficulty:proof.difficulty,issuedAt:proof.issuedAt,notBefore:proof.notBefore,expiresAt:proof.expiresAt,nonceStart:proof.nonceStart,nonceEnd:proof.nonceEnd};const challenge=workChallenge(template);if(challenge!==proof.challenge)throw new Error("Work challenge mismatch");const digest=powDigest(challenge,block.nonce);if(digest!==proof.powHash||!meetsDifficulty(digest,proof.difficulty))throw new Error("Invalid client proof of work");const message=miningSubmissionMessage({templateId:proof.templateId,nonce:block.nonce,powHash:proof.powHash,timestamp:proof.submittedAt});if(!cryptoProvider.verify(message,proof.signature,proof.publicKey))throw new Error("Invalid work proof signature");if(proof.difficulty!==NETWORK.difficulty)throw new Error("Unexpected work difficulty");if(proof.submittedAt<proof.notBefore||proof.submittedAt>proof.expiresAt)throw new Error("Work proof timing is invalid");return true};
const storedTransactionMessage=tx=>tx.version>=3?`${tx.from}|${tx.to}|${tx.amount}|${tx.timestamp}|${tx.gasPrice}|${tx.gasLimit}|${tx.addressScheme}`:tx.version>=2?`${tx.from}|${tx.to}|${tx.amount}|${tx.timestamp}|${tx.gasPrice}|${tx.gasLimit}`:`${tx.from}|${tx.to}|${tx.amount}|${tx.timestamp}`;
const validateStoredTransaction=(tx,block,index)=>{if(!tx||!/^krk1[0-9a-f]{40}$/.test(tx.to)||!/^krk1[0-9a-f]{40}$/.test(tx.from)||!Number.isSafeInteger(Number(tx.timestamp))||BigInt(tx.amount)<=0n)throw new Error("Invalid persisted transaction");const version=Number(tx.version||1),scheme=version>=3?tx.addressScheme:"transparent-v1",gasUsed=version>=2?GAS.transferLimit:0n,gasPrice=version>=2?BigInt(tx.gasPrice):0n;if(![1,2,3].includes(version)||!['transparent-v1','wormhole-v1'].includes(scheme)||BigInt(tx.gasUsed)!==gasUsed||BigInt(tx.fee)!==gasUsed*gasPrice||addressFromPublicKey(tx.publicKey,scheme)!==tx.from)throw new Error("Invalid persisted transaction fields");const message=storedTransactionMessage({...tx,version,addressScheme:scheme});if(tx.id!==sha256(message+tx.signature)||!cryptoProvider.verify(message,tx.signature,tx.publicKey))throw new Error("Invalid persisted transaction signature");if(block&&(tx.status!=="confirmed"||tx.blockHeight!==block.height||tx.transactionIndex!==index))throw new Error("Invalid persisted transaction placement");return{fee:BigInt(tx.fee),gasUsed}};
const validateSnapshotAccounting=state=>{let rewardCount=0,runningFees=0n,totalRewards=0n;for(const block of state.chain.slice(1)){let fees=0n,gas=0n;(block.transactions||[]).forEach((tx,index)=>{const checked=validateStoredTransaction(tx,block,index);fees+=checked.fee;gas+=checked.gasUsed});if(BigInt(block.fees)!==fees||BigInt(block.gasUsed)!==gas)throw new Error(`Invalid persisted block accounting at height ${block.height}`);const reward=BigInt(block.reward);if(reward>0n){const expected=rewardAtHeight(rewardCount),split=splitSubsidy(expected);if(block.rewardHeight!==rewardCount||reward!==expected||BigInt(block.minerReward)!==split.miner||BigInt(block.treasuryReward)!==split.treasury||block.treasuryAddress!==NETWORK.treasuryAddress||BigInt(block.feePayout)!==runningFees+fees)throw new Error(`Invalid persisted reward at height ${block.height}`);rewardCount++;totalRewards+=reward;runningFees=0n}else{if(BigInt(block.feePayout)!==0n)throw new Error(`Invalid persisted fee payout at height ${block.height}`);runningFees+=fees}}for(const tx of state.pending||[])validateStoredTransaction(tx,null,null);if(rewardCount!==Number(state.rewardBlockCount)||totalRewards!==BigInt(state.minedSupply)||runningFees!==BigInt(state.feePool))throw new Error("Persisted counters are inconsistent");const faucet=BigInt(state.testnetFaucetSupply||0),balances=state.balances||[],liquid=balances.reduce((sum,[,balance])=>sum+BigInt(balance),0n);if(faucet<0n||!Array.isArray(balances)||new Set(balances.map(([address])=>address)).size!==balances.length||balances.some(([address,balance])=>!/^krk1[0-9a-f]{40}$/.test(address)||BigInt(balance)<0n)||liquid>totalRewards+faucet)throw new Error("Persisted balances are inconsistent")};
export class KorekChain{
 constructor(){this.pending=[];this.transactionIds=new Set();this.balances=new Map();this.minedSupply=0n;this.testnetFaucetSupply=0n;this.rewardBlockCount=0;this.feePool=0n;this.faucetClaims=new Map();this.chain=[this.genesis()]}
 genesis(){const block={height:0,rewardHeight:null,previousHash:"0".repeat(64),timestamp:1735689600000,transactions:[],miner:"genesis",usefulWork:{type:"genesis",score:0},reward:"0",gasUsed:"0",fees:"0",nonce:0};return{...block,hash:hashBlock(block)}}
 addTransaction(input,receivedAt=Date.now()){
  const required=["from","to","amount","publicKey","signature","timestamp"];if(!input||!required.every(key=>input[key]!==undefined))throw new Error("Incomplete transaction");if(this.pending.length>=MEMPOOL.maxTransactions)throw new Error("Mempool is full");
  const timestamp=Number(input.timestamp),numeric=value=>/^\d+$/.test(String(value))&&String(value).length<=MEMPOOL.maxNumericDigits;if(!Number.isSafeInteger(timestamp)||timestamp<receivedAt-MEMPOOL.maxAgeMs||timestamp>receivedAt+MEMPOOL.maxFutureMs)throw new Error("Transaction timestamp is outside the allowed window");if(typeof input.publicKey!=="string"||Buffer.byteLength(input.publicKey)>MEMPOOL.maxPublicKeyBytes||typeof input.signature!=="string"||Buffer.byteLength(input.signature)>MEMPOOL.maxSignatureBytes)throw new Error("Transaction authentication data is too large");if(!/^krk1[0-9a-f]{40}$/.test(input.to)||!numeric(input.amount)||BigInt(input.amount)<=0n)throw new Error("Invalid transfer");
  const version=Number(input.version||1);if(!Number.isInteger(version)||version<1||version>3||version>=2&&(!numeric(input.gasPrice)||!numeric(input.gasLimit)))throw new Error("Unsupported or malformed transaction version");const gasPrice=version>=2?BigInt(input.gasPrice):0n,gasLimit=version>=2?BigInt(input.gasLimit):0n,addressScheme=version>=3?String(input.addressScheme||"transparent-v1"):"transparent-v1";
  if(!["transparent-v1","wormhole-v1"].includes(addressScheme))throw new Error("Unsupported address scheme");if(version>=2&&(gasPrice<GAS.price||gasLimit<GAS.transferLimit))throw new Error("Gas price or gas limit is too low");
  const gasUsed=version>=2?GAS.transferLimit:0n,fee=gasUsed*gasPrice;const message=version>=3?`${input.from}|${input.to}|${input.amount}|${input.timestamp}|${gasPrice}|${gasLimit}|${addressScheme}`:version>=2?`${input.from}|${input.to}|${input.amount}|${input.timestamp}|${gasPrice}|${gasLimit}`:`${input.from}|${input.to}|${input.amount}|${input.timestamp}`;
  if(addressFromPublicKey(input.publicKey,addressScheme)!==input.from)throw new Error("Public key mismatch");if(!cryptoProvider.verify(message,input.signature,input.publicKey))throw new Error("Invalid signature");
  const reserved=this.pending.filter(tx=>tx.from===input.from).reduce((sum,tx)=>sum+BigInt(tx.amount)+BigInt(tx.fee),0n);if((this.balances.get(input.from)||0n)-reserved<BigInt(input.amount)+fee)throw new Error("Insufficient balance for amount and network fee");
  const tx={...input,timestamp,version,addressScheme,gasPrice:gasPrice.toString(),gasLimit:gasLimit.toString(),gasUsed:gasUsed.toString(),fee:fee.toString(),sentAt:timestamp,receivedAt,status:"pending",blockHeight:null,transactionIndex:null,confirmedAt:null};tx.id=sha256(message+input.signature);if(this.transactionIds.has(tx.id))throw new Error("Duplicate transaction");this.transactionIds.add(tx.id);this.pending.push(tx);return tx;
 }
 mine(miner,usefulWork={type:"benchmark",score:0},now=Date.now(),options={}){if(!/^krk1[0-9a-f]{40}$/.test(miner))throw new Error("Invalid miner address");const height=this.chain.length,rewardEnabled=options.rewardEnabled!==false,difficulty=options.difficulty??NETWORK.difficulty,payout=rewardEnabled?expectedPayout(this):{reward:0n,minerReward:0n,treasuryReward:0n,feePayout:0n},transactions=this.pending.splice(0);let fees=0n,gasUsed=0n;transactions.forEach((tx,index)=>{tx.status="confirmed";tx.blockHeight=height;tx.transactionIndex=index;tx.confirmedAt=now;tx.confirmationTimeMs=Math.max(0,now-tx.receivedAt);fees+=BigInt(tx.fee);gasUsed+=BigInt(tx.gasUsed)});if(rewardEnabled)payout.feePayout+=fees;else this.feePool+=fees;const block={height,rewardHeight:rewardEnabled?this.rewardBlockCount:null,previousHash:this.chain.at(-1).hash,timestamp:now,transactions,miner,usefulWork,reward:payout.reward.toString(),minerReward:payout.minerReward.toString(),treasuryReward:payout.treasuryReward.toString(),treasuryAddress:NETWORK.treasuryAddress,gasUsed:gasUsed.toString(),fees:fees.toString(),feePayout:payout.feePayout.toString(),nonce:0};const target="0".repeat(difficulty);do{block.nonce++;block.hash=hashBlock(block)}while(!block.hash.startsWith(target));for(const tx of transactions){this.balances.set(tx.from,(this.balances.get(tx.from)||0n)-BigInt(tx.amount)-BigInt(tx.fee));this.balances.set(tx.to,(this.balances.get(tx.to)||0n)+BigInt(tx.amount))}if(rewardEnabled){this.balances.set(miner,(this.balances.get(miner)||0n)+payout.minerReward+payout.feePayout);this.balances.set(NETWORK.treasuryAddress,(this.balances.get(NETWORK.treasuryAddress)||0n)+payout.treasuryReward);this.feePool=0n;this.minedSupply+=payout.reward;this.rewardBlockCount++}this.chain.push(block);return block}
 miningTemplateData(miner,now=Date.now()){if(!/^krk1[0-9a-f]{40}$/.test(miner))throw new Error("Invalid miner address");if(this.pending.length)throw new Error("Pending transactions must be sealed before issuing work");const payout=expectedPayout(this);return{networkId:NETWORK.networkId,height:this.chain.length,previousHash:this.chain.at(-1).hash,rewardAddress:miner,reward:payout.reward.toString(),minerReward:payout.minerReward.toString(),treasuryReward:payout.treasuryReward.toString(),treasuryAddress:NETWORK.treasuryAddress,feePayout:payout.feePayout.toString(),difficulty:NETWORK.difficulty,notBefore:Math.max(now,this.chain.at(-1).timestamp+NETWORK.rewardBlockTimeMs),now}}
 acceptClientProof(template,submission){if(this.pending.length)throw new Error("Chain state changed; request new work");if(template.height!==this.chain.length||template.previousHash!==this.chain.at(-1).hash)throw new Error("Stale work template");const payout=expectedPayout(this);if(template.reward!==payout.reward.toString()||template.minerReward!==payout.minerReward.toString()||template.treasuryReward!==payout.treasuryReward.toString()||template.treasuryAddress!==NETWORK.treasuryAddress||template.feePayout!==payout.feePayout.toString())throw new Error("Mining payout changed; request new work");const block={height:template.height,rewardHeight:this.rewardBlockCount,previousHash:template.previousHash,timestamp:submission.timestamp,transactions:[],miner:template.rewardAddress,usefulWork:{type:"client-pow",score:Number(submission.hashesTried||0),device:String(submission.device||"cpu")},reward:template.reward,minerReward:template.minerReward,treasuryReward:template.treasuryReward,treasuryAddress:template.treasuryAddress,gasUsed:"0",fees:"0",feePayout:template.feePayout,nonce:submission.nonce,workProof:{protocol:MINER_PROTOCOL_V3,templateId:template.templateId,challenge:template.challenge,difficulty:template.difficulty,issuedAt:template.issuedAt,notBefore:template.notBefore,expiresAt:template.expiresAt,nonceStart:template.nonceStart,nonceEnd:template.nonceEnd,powHash:submission.powHash,publicKey:submission.publicKey,signature:submission.signature,submittedAt:submission.timestamp}};validateClientProof(block);block.hash=hashBlock(block);this.balances.set(block.miner,(this.balances.get(block.miner)||0n)+BigInt(block.minerReward)+BigInt(block.feePayout));this.balances.set(NETWORK.treasuryAddress,(this.balances.get(NETWORK.treasuryAddress)||0n)+BigInt(block.treasuryReward));this.feePool=0n;this.minedSupply+=BigInt(block.reward);this.rewardBlockCount++;this.chain.push(block);return block}
 sealPending(now=Date.now()){return this.pending.length===0?null:this.mine(NETWORK.nodeMinerAddress,{type:"rapid-testnet-finality",score:1},now,{difficulty:0,rewardEnabled:false})}
 balance(address){return(this.balances.get(address)||0n).toString()}
 cumulativeWork(){return this.chain.reduce((total,block)=>total+blockWork(block),0n)}
 transactions(limit=50){return[...this.pending].reverse().concat(this.chain.slice(1).reverse().flatMap(block=>[...block.transactions].reverse())).slice(0,limit)}
 transaction(id){const tx=this.pending.find(x=>x.id===id)||this.chain.flatMap(block=>block.transactions).find(x=>x.id===id);return tx?{...tx,confirmations:tx.blockHeight===null?0:this.chain.length-tx.blockHeight}:null}
 block(id){const block=/^\d+$/.test(String(id))?this.chain[Number(id)]:this.chain.find(x=>x.hash===id);return block?{...block,confirmations:this.chain.length-block.height,sizeBytes:Buffer.byteLength(JSON.stringify(block))}:null}
 claimFaucet(address,amount=100n*100_000_000n,now=Date.now()){if(!/^krk1[0-9a-f]{40}$/.test(address))throw new Error("Invalid KOREK address");const cooldown=3_600_000,previous=this.faucetClaims.get(address)||0;if(now-previous<cooldown)throw new Error(`Faucet cooldown active. Try again in ${Math.max(1,Math.ceil((cooldown-(now-previous))/60_000))} minutes`);this.balances.set(address,(this.balances.get(address)||0n)+amount);this.testnetFaucetSupply+=amount;this.faucetClaims.set(address,now);return{address,amount:amount.toString(),balance:this.balance(address),network:NETWORK.networkId,claimedAt:now,nextClaimAt:now+cooldown}}
 snapshot(){return{version:1,networkId:NETWORK.networkId,chain:this.chain,pending:this.pending,balances:[...this.balances].map(([address,balance])=>[address,balance.toString()]),minedSupply:this.minedSupply.toString(),testnetFaucetSupply:this.testnetFaucetSupply.toString(),rewardBlockCount:this.rewardBlockCount,feePool:this.feePool.toString(),faucetClaims:[...this.faucetClaims]}}
 static fromSnapshot(state){if(state?.version!==1||state.networkId!==NETWORK.networkId||!Array.isArray(state.chain)||state.chain.length===0)throw new Error("Unsupported chain state");const restored=new KorekChain();for(let index=0;index<state.chain.length;index++){const block=state.chain[index];if(block.height!==index||block.hash!==hashBlock(block)||(index>0&&block.previousHash!==state.chain[index-1].hash))throw new Error(`Invalid persisted block at height ${index}`);if(block.workProof)validateClientProof(block)}const mined=BigInt(state.minedSupply),rewardTotal=state.chain.reduce((sum,block)=>sum+BigInt(block.reward),0n);if(mined!==rewardTotal||mined<0n||mined>NETWORK.miningAllocation)throw new Error("Persisted mining supply is invalid");validateSnapshotAccounting(state);restored.chain=state.chain;restored.pending=Array.isArray(state.pending)?state.pending:[];restored.transactionIds=new Set([...state.chain.flatMap(block=>block.transactions||[]),...restored.pending].map(tx=>tx.id));if(restored.transactionIds.size!==state.chain.reduce((sum,block)=>sum+(block.transactions||[]).length,0)+restored.pending.length)throw new Error("Persisted transaction replay detected");restored.balances=new Map((state.balances||[]).map(([address,balance])=>[address,BigInt(balance)]));restored.minedSupply=mined;restored.testnetFaucetSupply=BigInt(state.testnetFaucetSupply||0);restored.rewardBlockCount=Number(state.rewardBlockCount||0);restored.feePool=BigInt(state.feePool||0);restored.faucetClaims=new Map(state.faucetClaims||[]);return restored}
 status(){return{...NETWORK,maxSupply:NETWORK.maxSupply.toString(),miningAllocation:NETWORK.miningAllocation.toString(),genesisPremine:NETWORK.genesisPremine.toString(),minerShareBps:NETWORK.minerShareBps.toString(),treasuryShareBps:NETWORK.treasuryShareBps.toString(),minerTargetAllocation:(NETWORK.maxSupply*NETWORK.minerShareBps/10_000n).toString(),treasuryTargetAllocation:(NETWORK.maxSupply*NETWORK.treasuryShareBps/10_000n).toString(),minedSupply:this.minedSupply.toString(),issued:this.minedSupply.toString(),testnetFaucetSupply:this.testnetFaucetSupply.toString(),rewardBlockCount:this.rewardBlockCount,feePool:this.feePool.toString(),cumulativeWork:this.cumulativeWork().toString(),height:this.chain.length-1,pending:this.pending.length,transactions:this.chain.reduce((sum,b)=>sum+b.transactions.length,0),gasPrice:GAS.price.toString(),transferGas:GAS.transferLimit.toString(),crypto:cryptoProvider.algorithm}}
}
